services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-role-based-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass

volumes:
  db_data:
  mongo_data:
